### ISSUE TITLE
Add bow damage configurations

### ISSUE THREAD

**Issue by purejosh** [kwpugh/EmeraldTools#29]
Please add bow damage configuration to the .json file, so we can nerf these bows. They can two shot an iron golem, when enchanted with power V.

**Comment by kwpugh** [comment]
I'll take a look at doing this.

**Comment by kwpugh** [comment]
Updated in Emerald Tools and MoreGems

**Comment by purejosh** [comment]
That was fast. I'm impressed! Thank you!

**Comment by purejosh** [comment]
Hello. Per this github, there should be bow damage configurations available in the .json5, however there are no signs of that in the file. There are zoom configs, but no configs regarding damage output from the bows. 
The vanilla bow does up to 11 damage, and the custom bows do up to 23, and I really would like to nerf it.

**Comment by purejosh** [comment]
EmeraldTools-Fabric-1.18.2-1.3.46 is the one I've tested. 
I did not regen my config. I'm going to try that now.

**Comment by kwpugh** [comment]
Ahh.  I added those to 1.19, which is current supported version.  I generally do not back port new features.

**Comment by purejosh** [comment]
Ohh, that makes sense... 

I mean, I won't ask you to do what you don't want to do, but. It is what it is, I suppose. 
I guess I'll be on 1.19 eventually, when Mojang stops updating 1.19.1. 

Thanks for the prompt response.

**Comment by kwpugh** [comment]
I'm in the process of adding the freatures to 1.18.2 now.

How are you memasuring the damage from bows?

**Comment by purejosh** [comment]
Wow, you're awesome! 

I use a mod called MmmMmmMmmMmm. It's a dummy that outputs the raw damage you hit it with. Very useful.

**Comment by kwpugh** [comment]
Yes, I just found that.  It is proving useful to confirm actual damage by bows.  The new default settings in the config will be close to vanilla with the ability to tweak higher if desired.

**Comment by kwpugh** [comment]
Look for v47 on curse forge shortly....

Let me know how your results come out

**Comment by purejosh** [comment]
Excellent. I will test in about an hour and provide feedback here!

**Comment by kwpugh** [comment]
Not sure if you are a member of my discord, but I post a note for more info:


Hi all.

I'm introducing new options for gem bows in Emerald Tools 

Background things of note:
- the damage of an un-enchanted bow is computed by the game using "velocity", with velocity being a product of pitch, yaw, roll, speed, and divergence.  Sin, cos, and atan are involved, so it is complicated.  Speed has the strongest influence on damage
- vanilla hard codes speed =3 and divergence = pull progress value * 3.  The closer the divergence value gets to 0, the more accurate the shot will be

Get that, I have added new config options for tweaking:
- speed - 3.0 is vanilla default, increasing this value will increase damage.  6.0 is pretty OP for reference
- divergence - default is 0.0 because I like that.  move it higher to be less accurate (values up .75 or so)
- roll - not really used by players, more for my testing
- power damage bonus - 0.5 is close to the vanilla default, 0.75 pretty much doubles Power V on a vanilla bow
- extra damage - just plain old brute force extra damage, default at 0, if set to 5 it will and 5 damage on top of everything else

Let me know how it works out for you.  I plan to add these options to Gobber and MoreGems in the near future, with different default values though

**Comment by purejosh** [comment]
I gotcha. So, increasing speed (therefore reducing drop) isn't possible without directly affecting damage output. 

I'm still doing some testing, but the options themselves appear to be working just fine. Will the mod accept a negative value?

Also, fwiw, there's a model issue with pulling_0 and the other pulling states. It appears to be shifted down a bit during pulling_0, but bumps higher for pulling_1-3.

**Comment by purejosh** [comment]
Yes, the mod will accept negative values. 

```
	   ******************************
	   Global Gem Bow Settings
	   ******************************
	*/
	"projectileSpeed": 5.0,
	"projectileDivergence": 0.0,
	"projectileRoll": 0.0,
	"projectilePowerDamageBonus": 0.5,
	"projectileExtraDamage": -1.0,
	/* 
```

17-25 Vanilla bow, P5
20-28 Gem bow, P5

So, by setting speed up to 5, which is a lovely feeling compared to the vanilla bows that drop so aggressively, and giving it a negative offset for extra damage, I can essentially curate a perfect balance between the two.

**Comment by kwpugh** [comment]
wonderful, glad that works for you.

**Comment by purejosh** [comment]
You don't want/need a new github for the texture adjustments, right?

**Comment by purejosh** [comment]
Also, I very much appreciate you updating this version with this amazing new code.

**Comment by kwpugh** [comment]
honestly, I'm not sure what you mean.   the textures are my weak point.

**Comment by purejosh** [comment]
With the gem bows, it shifts upwards very slightly when it passes from the first stage of pulling to the second stage. You can observe that in the vanilla bow, the pulling is very smooth. 
https://user-images.githubusercontent.com/70633949/181639706-14e73032-db84-4179-86f0-f4ea0d588871.mp4
